name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: create a ZIP file
        run: zip -r release.zip practices/ chap* LICENSE.txt README.md &&
          unzip -t release.zip
      - name: Build
        run: echo ${{ github.sha }} > Release.txt
      - name: Test
        run: cat Release.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: | 
            Release.txt
            release.zip

        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # with:
        #   tag_name: ${{ github.ref }}
        #   release_name: Release ${{ github.ref }}
        #   draft: false
        #   prerelease: false

        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # with:
        #   upload_url: ${{ steps.create_release.outputs.upload_url }}
        #   asset_path: ./release.zip
        #   asset_name: sukkiri-javap4-codes.zip
        #   asset_content_type: application/zip
